[workspace]
members = ["pkg/base", "pkg/pro"]
resolver = "2"

[profile.release]
lto = true
debug = true
#^ needed to produce debug info at all
# see https://doc.rust-lang.org/rustc/codegen-options/index.html#debug
