# TODO: cached
name: Rust CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  # linkCheck:
  #   name: check links
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Link Checker
  #       id: lychee
  #       uses: lycheeverse/lychee-action@v1.8.0
  #     # - name: Create Issue From File
  #     #   if: env.lychee_exit_code != 0
  #     #   uses: peter-evans/create-issue-from-file@v4
  #     #   with:
  #     #     title: Link Checker Report
  #     #     content-filepath: ./lychee/out.md
  #     #     labels: report, automated issue
  #     # uses: ludeeus/action-shellcheck@2
  unitTests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            pkg/base
            pkg/pro
      - run: cargo fmt --check
      - run: cargo clippy --all-features
      - run: cargo test --all-features
