name: build and release
on:
  workflow_dispatch: # for manual debugging
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-bin:
    strategy:
      fail-fast: false # to see what builds/what fails
      matrix:
        include:
          # each `target` is picked from `rustup target list` and each
          # `vscode-target` is drawn from `vsce publish --help`
          # x86 windows
          - os: windows-latest
            native:
              target: x86_64-pc-windows-msvc
              vscode-target: win32-x64
          - os: ubuntu-latest
            native:
              target: x86_64-unknown-linux-gnu
              vscode-target: linux-x64 # todo: fully-static MUSL?
              zig: false
            cross:
              target: aarch64-unknown-linux-gnu
              vscode-target: linux-arm64
              zig: true
          - os: macos-latest
            native:
              target: x86_64-apple-darwin
              vscode-target: darwin-x64x
              zig: true
            cross:
              target: aarch64-apple-darwin
              vscode-target: darwin-arm64
              zig: true

    name: Build (${{ matrix.native.target }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # shallow clone for speed
      - name: "cache native binary build: ${{ matrix.native.target }}"
        uses: actions/cache@v3
        id: native-cache
        with:
          path: |
            ./target/${{ matrix.native.target }}/release/base_language_server*
            ./target/${{ matrix.native.target }}/release/base_language_server.exe
            ./target/${{ matrix.native.target }}/release/base_language_server.pdb
          # hardcode paths in an attempt to appease windows
          key: ${{ matrix.native.target }}--${{ hashFiles('./Cargo.lock', '**/Cargo.toml', 'pkg/base/**/*.rs', 'pkg/base/**/*.scm', './scripts/build_bin.sh') }}
      - name: "cache cross binary build: ${{ matrix.cross.target }}"
        uses: actions/cache@v3
        if: matrix.cross.target
        id: cross-cache
        with:
          path: ./target/${{ matrix.cross.target }}/release/base_language_server*
          key: ${{ matrix.cross.target }}--${{ hashFiles('./Cargo.lock', '**/Cargo.toml', 'pkg/base/**/*.rs', 'pkg/base/**/*.scm') }}
      - id: boot
        shell: bash
        run: |
          native="${{ steps.native-cache.outputs.cache-hit != 'true' || false }}"
          cross="${{ matrix.cross.target && steps.cross-cache.outputs.cache-hit != 'true' || false }}"
          {
            case "$native/$cross" in
              false/false) echo "init=false" ;;
              *) echo "init=true" ;;
            esac
            echo "native=$native"
            echo "cross=$cross"
          } | tee -a $GITHUB_OUTPUT
      - name: set MacOS SDKROOT and MACOSX_DEPLOYMENT_TARGET
        # see https://stackoverflow.com/questions/66849112/how-do-i-cross-compile-a-rust-application-from-macos-x86-to-macos-silicon
        if: matrix.os == 'macos-latest' && steps.boot.outputs.init == 'true'
        run: |
          {
            echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)"
            echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)"
          } | tee -a $GITHUB_ENV
      - name: "Install rust toolchain"
        if: steps.boot.outputs.init == 'true'
        shell: bash
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add rust-src
          rustup component add llvm-tools-preview # 32mb
        # pulling 3x32MB of llvm tools is still better than pushing+pulling
        # 6x60MB of the built binary
      - name: "install native rust target: ${{ matrix.native.target }}"
        shell: bash
        if: steps.boot.outputs.native == 'true'
        run: rustup target add ${{ matrix.native.target }}
      - uses: Swatinem/rust-cache@v2 # see https://github.com/Swatinem/rust-cache
        if: steps.boot.outputs.init == 'true'
      - name: setup zig
        if: steps.boot.outputs.init == 'true'
        shell: bash
        run: python3 -m pip install ziglang cargo-zigbuild
      - name: modify $PATH
        shell: bash
        if: steps.boot.outputs.init == 'true'
        run: |
          {
            site_packages="$(
              python3 -c 'import sys, pathlib as p; [
                print(i) for i in sys.path
                if p.Path(i).name == "site-packages"
              ]'
            )"
            _sysroot="$(rustup run stable rustc --print sysroot)"
            bins_dir="$_sysroot/lib/rustlib/${{ matrix.native.target }}/bin"
            export PATH="$bins_dir:$site_packages/ziglang:$PATH"
            echo "PATH=$PATH"
          } | tee -a $GITHUB_ENV | tr ':' '\n' | sed 's/^/ -  /g'
      - name: "native build: ${{ matrix.native.target }}"
        shell: bash
        if: steps.native-cache.outputs.cache-hit != 'true'
        run: |
          target="${{ matrix.native.target }}"
          use_zig="${{ matrix.native.zig || 'false' }}"
          export RUSTFLAGS="-Clink-args=-Wl,--build-id=sha1"
          ./scripts/build_bin.sh                      \
            --version=base                            \
            --profile=release                         \
            --target="$target"                        \
            --zig="$use_zig"

      - name: "upload native bin: ${{ matrix.native.target }}"
        uses: actions/upload-artifact@v3
        with:
          name: cconvention-base-${{matrix.native.target}}
          path: ./target/${{matrix.native.target}}/release/base_language_server*
      - name: "add rustup cross-compilation target: ${{ matrix.cross.target || 'none' }}"
        if: steps.boot.outputs.cross == 'true'
        shell: bash
        run: rustup target add ${{ matrix.cross.target }}
      - name: "cross build: ${{ matrix.cross.target || 'none' }}"
        if: matrix.cross.target && steps.cross-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          target="${{ matrix.cross.target }}"
          use_zig="${{ matrix.cross.zig || 'false' }}"
          export RUSTFLAGS="-Clink-args=-Wl,--build-id=sha1"
          ./scripts/build_bin.sh                      \
            --version=base                            \
            --profile=release                         \
            --target="$target"                        \
            --zig="$use_zig"
      - name: "upload cross bin: ${{ matrix.cross.target }}"
        if: matrix.cross.target
        uses: actions/upload-artifact@v3
        with:
          name: cconvention-base-${{matrix.cross.target}}
          path: ./target/${{matrix.cross.target}}/release/base_language_server*
  build-js:
    name: Bundle VSCode extension JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # shallow clone for speed
      - name: cache the built JS
        uses: actions/cache@v3
        id: built-base-js
        with:
          path: ./editors/code/base/dist/main.min.common.js
          key: "built-js-for-${{ hashfiles('./editors/code/base/src/*.ts', './editors/code/base/pnpm-lock.yaml') }}"
      - uses: pnpm/action-setup@v2 # see https://github.com/pnpm/action-setup
        if: steps.built-base-js.outputs.cache-hit != 'true'
        with:
          version: 8
      - uses: actions/setup-node@v3 # see https://github.com/actions/setup-node/
        if: steps.built-base-js.outputs.cache-hit != 'true'
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: |
            ./editors/code/base/pnpm-lock.yaml
            ./editors/code/pro/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: editors/code/base
        if: steps.built-base-js.outputs.cache-hit != 'true'
      - name: modify $PATH
        shell: bash
        working-directory: ./editors/code/base
        run: |
          export PATH=${PWD}/node_modules/.bin:$PATH
          echo PATH=$PATH | tee -a $GITHUB_ENV
      - name: check the tmLanguage up-to-date
        if: steps.built-base-js.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ./editors/code/base
        run: |
          ./scripts/build_textmate.sh
          git --no-pager diff --exit-code -- src/tmLanguage.json
      - name: build the JS if changed
        shell: bash
        if: steps.built-base-js.outputs.cache-hit != 'true'
        working-directory: ./editors/code/base
        run: ./scripts/build_js.sh
      - name: upload bundled JS
        uses: actions/upload-artifact@v3
        with:
          name: main-js
          path: ./editors/code/base/dist/main.min.common.js
  build-vsix:
    name: Build VSCode extensions
    needs: [build-bin, build-js]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # to see what builds/what fails
      matrix:
        include:
          - os: windows-latest
            native:
              target: x86_64-pc-windows-msvc
              vscode-target: win32-x64
          - os: ubuntu-latest
            native:
              target: x86_64-unknown-linux-gnu
              vscode-target: linux-x64 # todo: fully-static MUSL?
            cross:
              target: aarch64-unknown-linux-gnu
              vscode-target: linux-arm64
          - os: macos-latest
            native:
              target: x86_64-apple-darwin
              vscode-target: darwin-x64x
            cross:
              target: aarch64-apple-darwin
              vscode-target: darwin-arm64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # shallow clone for speed
      - name: "download native binary: ${{ matrix.native.target }}"
        uses: actions/download-artifact@v3
        # https://github.com/actions/download-artifact
        with:
          name: cconvention-base-${{ matrix.native.target }}
          path: ./target/${{ matrix.native.target }}/release/
      - name: "download bundled JS"
        uses: actions/download-artifact@v3
        with:
          name: main-js
          path: ./editors/code/base/dist/
      - name: "download cross binary: ${{ matrix.cross.target || '<skip>' }}"
        uses: actions/download-artifact@v3
        if: matrix.cross.target
        with:
          name: cconvention-base-${{ matrix.cross.target }}
          path: ./target/${{ matrix.cross.target }}/release/
      - name: derive paths
        id: paths
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest)  bin_suffix="";     debug_suffix=".debug" ;;
            windows-latest) bin_suffix=".exe"; debug_suffix=".pdb"   ;;
            macos-latest)   bin_suffix=""    ; debug_suffix=".dSYM"  ;;
          esac
          native_bin="${PWD}/target/${{ matrix.native.target }}/release/base_language_server$bin_suffix"
          native_debug="${PWD}/target/${{ matrix.native.target }}/release/base_language_server$debug_suffix"
          cross_bin="${PWD}/target/${{ matrix.cross.target }}/release/base_language_server$bin_suffix"
          cross_debug="${PWD}/target/${{ matrix.cross.target }}/release/base_language_server$debug_suffix"

          {
            echo "native_bin=$native_bin"
            echo "native_debug=$native_debug"
            echo "cross_bin=$cross_bin"
            echo "cross_debug=$cross_debug"
          } | tee -a $GITHUB_OUTPUT

          stat $native_bin || {
            echo "$native_bin not found"
            ls -al ./target/${{ matrix.native.target }}/release/
            find ./target/${{ matrix.native.target }}/release/ -name 'base_language_server*'
          }
          stat $native_debug || echo "$native_debug not found"
          stat $cross_bin || echo "$cross_bin not found"
          stat $cross_debug || echo "$cross_debug not found"
      - uses: pnpm/action-setup@v2 # see https://github.com/pnpm/action-setup
        with:
          version: 8
      - uses: actions/setup-node@v3 # see https://github.com/actions/setup-node/
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: |
            ./editors/code/base/pnpm-lock.yaml
            ./editors/code/pro/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: editors/code/base
      - name: modify $PATH
        shell: bash
        working-directory: ./editors/code/base
        run: |
          export PATH=${PWD}/node_modules/.bin:$PATH
          echo PATH=$PATH | tee -a $GITHUB_ENV
      - name: "check native debuginfo: ${{ matrix.native.target }}"
        run: |
          command -v sentry-cli || echo "missing sentry-cli"

          bin=${{ steps.paths.outputs.native_bin }}
          debug=${{ steps.paths.outputs.native_debug }}
          echo bin=$bin
          stat $bin || echo "$bin not found"
          sentry-cli debug-files check $bin
          if [ -e "$debug" ]; then
            sentry-cli debug-files check $debug
          else
            echo "$debug not found"
          fi

      - name: build the ${{ matrix.native.vscode-target }} vsix
        shell: bash
        run: |
          ./scripts/build_vsix.sh \
            --version=base        \
            --profile=release     \
            --target=${{ matrix.native.target }}
      - name: upload ${{ matrix.native.vscode-target }} vsix
        uses: actions/upload-artifact@v3
        with:
          name: cconvention-${{matrix.native.vscode-target}}.vsix
          path: ./editors/code/base/dist/cconvention.${{ matrix.native.vscode-target }}.vsix

      - name: "check cross debuginfo: ${{ matrix.cross.target || '<skip>'}}"
        if: matrix.cross.target
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then suffix=".exe";
          else suffix=""
          fi

          bin=./target/${{ matrix.native.target }}/release/base_language_server$suffix
          sentry-cli debug-files check $bin
      - name: build the ${{ matrix.cross.vscode-target }} vsix
        if: matrix.cross.target
        shell: bash
        run: |
          ./scripts/build_vsix.sh \
            --version=base        \
            --profile=release     \
            --target=${{ matrix.cross.target }}
      - name: upload ${{ matrix.cross.vscode-target }} vsix
        if: matrix.cross.target
        uses: actions/upload-artifact@v3
        with:
          name: cconvention-${{matrix.cross.vscode-target}}.vsix
          path: ./editors/code/base/dist/cconvention.${{ matrix.cross.vscode-target }}.vsix

