name: shellcheck
on:
  workflow_dispatch:
    pull_request:
    paths:
      - "**.sh"
      - ".envrc"
  push:
    branches:
      - main
    paths:
      - "**.sh"
      - ".envrc"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@v2
        env:
          SHELLCHECK_OPTS: --external-sources --source-path=SCRIPTDIR
        with:
          check_together: "yes"
