name: debuggo
on:
  workflow_dispatch:
jobs:
  temp:
    runs-on: macos-latest
    steps:
      - name: debug
        run: |
          command -v xcodebuild
          xcodebuild -showsdks
          command -v xcrun
